### ISSUE TITLE
Visualization are not coming when running the app.

### ISSUE THREAD

**Issue by ankancode** [hnmr293/llama-viz#1]
Visualization are not coming when running the app.
<img width="1588" alt="Screenshot 2023-12-06 at 7 19 40 PM" src="https://github.com/hnmr293/llama-viz/assets/11076990/d8fe0b09-26be-4f24-81dc-11a07a5e2d03">

**Comment by hnmr293** [comment]
any messages in your terminal?

**Comment by ankancode** [comment]
No messages are coming on the terminal.

**Comment by hnmr293** [comment]
OK. I got it.

You have selected **Selected** mode in the *Visibility* section. In the **Selected** mode, you must select some tokens to get their graphs. You can select the tokens you wish by clicking them in the *Output* section.
For example, this is the case of selecting "The" and "capital" in the output: "The capital of India is New Delhi."

![image](https://github.com/hnmr293/llama-viz/assets/120772120/d26470de-f70c-4a8d-9d08-d1dbf5eb4d23)

If you want to see all graphs, select **All** in the *Visibility* section. Note that this requires an extremely long processing time if the number of generated tokens is large.

**Comment by zl-liu** [comment]
@hnmr293 @ankancode I faced the same issue. Even for a very short sentence such as "The capital of Canada is what", no visualization is shown. I am wondering if there is an error in the Gradio app that prevents the visualizations from showing up? Thank you!

Also, I am using Google Colab

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/queueing.py", line 495, in call_prediction
    output = await route_utils.call_process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1561, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1179, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 678, in wrapper
    response = f(*args, **kwargs)
  File "/content/llama-viz/main.py", line 22, in _hidden_states
    return hidden_states(_last_generation_result, *args, **kwargs)
  File "/content/llama-viz/ext/hidden_states.py", line 65, in hidden_states
    selected = json.loads(selected_json)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by zl-liu** [comment]
Is it because you set     graph = gr.Plot(visible=False) in ui.py? 

Thanks again for your help
